// MKS Service — accès frontend de démonstration. Une authentification serveur devra remplacer l’état local avant la production.
import { ArrowLeft, ArrowRight, Bell, BriefcaseBusiness, Building2, CheckCircle2, ChevronRight, CircleDollarSign, FileText, HardHat, LockKeyhole, LogOut, Menu, ShieldCheck, Users, X } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { getServices, publishService, removeService, type ServiceItem } from "../lib/catalog";

const internalAreas = [
  { hash: "#rh", name: "Espace RH", text: "Employés, contrats, présences et formations.", icon: Users, color: "green" },
  { hash: "#employer", name: "Espace Employé", text: "Missions, disponibilités, tâches et rapports.", icon: BriefcaseBusiness, color: "purple" },
  { hash: "#admin-principal", name: "Admin principal", text: "Vue globale, rôles et audit système.", icon: ShieldCheck, color: "navy" },
  { hash: "#admin-financier", name: "Admin financier", text: "Entrées, sorties et rapports financiers.", icon: CircleDollarSign, color: "orange" },
  { hash: "#admin-immobilier", name: "Admin immobilier", text: "Ventes, biens, commandes et clients.", icon: Building2, color: "blue" },
  { hash: "#admin-btp", name: "Admin BTP", text: "Devis, chantiers et contrats.", icon: FileText, color: "cyan" },
  { hash: "#admin-entretien", name: "Admin entretien & sécurité", text: "Services, équipes et interventions.", icon: LockKeyhole, color: "green" },
  { hash: "#responsable-rh", name: "Responsable RH", text: "Équipe, contrats, présences et formations.", icon: Users, color: "green" },
  { hash: "#responsable-btp", name: "Responsable BTP", text: "Chantiers, devis, équipes et réalisation.", icon: HardHat, color: "blue" },
  { hash: "#responsable-immobilier", name: "Responsable Immobilier", text: "Biens, ventes, visites et clients.", icon: Building2, color: "orange" },
  { hash: "#responsable-entretien", name: "Responsable Entretien", text: "Interventions, sécurité et suivi des sites.", icon: LockKeyhole, color: "green" },
];

function AccessForm({ onSuccess }: { onSuccess: () => void }) {
  const [register, setRegister] = useState(new URLSearchParams(window.location.search).get("mode") === "register");
  const [error, setError] = useState("");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); const service = new URLSearchParams(window.location.search).get("service"); if (service) sessionStorage.setItem("mks-pending-quote", service); sessionStorage.setItem("mks-client-session", "demo"); onSuccess(); };
  return <div className="access-form-shell"><div className="form-kicker"><LockKeyhole size={16} /> ACCÈS SÉCURISÉ · DÉMONSTRATION</div><h1>{register ? "Créer un compte." : "Ravi de vous revoir."}</h1><p>{register ? "Créez votre accès pour suivre vos demandes, devis et échanges." : "Connectez-vous pour retrouver vos demandes et l’avancement de vos projets."}</p><form onSubmit={submit}>{register && <label>Nom complet<input required name="name" placeholder="Votre nom" /></label>}<label>Adresse e-mail<input required type="email" name="email" placeholder="vous@exemple.com" /></label><label>Mot de passe<input required minLength={6} type="password" name="password" placeholder="••••••••" /></label>{error && <div className="form-error">{error}</div>}<button className="primary-action" type="submit">{register ? "Créer mon compte" : "Se connecter"} <ArrowRight size={16} /></button></form><button className="switch-form" onClick={() => setRegister(!register)}>{register ? "J’ai déjà un compte" : "Créer un compte"}</button><small className="demo-disclaimer">Mode démonstration : aucun compte réel n’est créé. L’authentification backend sera connectée ultérieurement.</small></div>;
}

export function LoginPage() {
  const success = () => { window.location.hash = "client"; window.history.replaceState({}, "", "/#client"); window.dispatchEvent(new HashChangeEvent("hashchange")); };
  return <main className="access-page"><a className="access-back" href="/#top"><ArrowLeft size={16} /> Retour au site public</a><div className="access-brand"><span className="mks-mark">MKS</span><strong>MKS SERVICE</strong></div><AccessForm onSuccess={success} /><div className="access-side"><div className="side-stamp">MKS<br /><small>ESPACE</small></div><h2>Votre projet,<br /><em>au même endroit.</em></h2><p>Retrouvez vos demandes, vos devis, vos échanges et votre historique depuis un espace simple.</p></div></main>;
}

function QuoteRequest({ serviceId }: { serviceId: string }) {
  const service = getServices().find((item) => item.id === serviceId);
  const [sent, setSent] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); sessionStorage.removeItem("mks-pending-quote"); };
  if (sent) return <div className="quote-success"><CheckCircle2 size={27} /><h2>Demande envoyée.</h2><p>Votre demande de devis a été enregistrée dans l’espace client de démonstration. MKS Service pourra vous répondre après connexion de l’API.</p><a href="#client">Retour à l’espace client</a></div>;
  return <div className="quote-request"><div className="public-kicker">DEMANDE DE DEVIS · {service?.category ?? "MKS SERVICE"}</div><h2>{service?.title ?? "Votre projet"}</h2><p>{service?.description ?? "Décrivez votre besoin pour recevoir une proposition."}</p><form onSubmit={submit}><label>Votre besoin<textarea required placeholder="Décrivez la quantité, le lieu ou le délai souhaité" /></label><label>Budget indicatif<input placeholder="Ex. À définir avec MKS Service" /></label><button className="primary-action" type="submit">Envoyer la demande <ArrowRight size={16} /></button></form></div>;
}

export function ClientDashboard({ onLogout }: { onLogout: () => void }) {
  const [menu, setMenu] = useState(false);
  const [quoteService, setQuoteService] = useState(() => sessionStorage.getItem("mks-pending-quote") ?? "");
  useEffect(() => { const update = () => setQuoteService(sessionStorage.getItem("mks-pending-quote") ?? ""); window.addEventListener("hashchange", update); return () => window.removeEventListener("hashchange", update); }, []);
  return <main className="workspace-page"><header className="workspace-header"><a className="mks-brand" href="/#top"><span className="mks-mark">MKS</span><span><strong>MKS</strong><small>SERVICE</small></span></a><div className="workspace-title"><span>ESPACE CLIENT</span><strong>Bonjour, votre projet avance.</strong></div><button className="workspace-menu" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button><button className="logout-button" onClick={onLogout}><LogOut size={15} /> Se déconnecter</button></header><div className="workspace-layout"><aside className={`workspace-sidebar ${menu ? "open" : ""}`}><small>MON ESPACE</small><a className="selected" href="#client">Vue d’ensemble</a><a href="#client-demandes">Mes demandes</a><a href="#client-devis">Devis & factures</a><a href="#client-messages">Messages</a><small>ACCÈS AUTORISÉS</small>{internalAreas.slice(0, 2).map(({ hash, name, icon: Icon }) => <a key={hash} href={`/${hash}`}>{<Icon size={14} />}{name}</a>)}</aside><section className="workspace-content"><div className="workspace-welcome"><div><div className="public-kicker">Vue d’ensemble · 24 juin 2026</div><h1>Votre activité<br /><em>en un regard.</em></h1></div><button className="primary-action">Nouvelle demande <ArrowRight size={16} /></button></div><div className="workspace-stats"><div><span>Demandes actives</span><strong>02</strong><small>Une en cours de traitement</small></div><div><span>Devis reçus</span><strong>01</strong><small>À consulter</small></div><div><span>Prochaine étape</span><strong>04</strong><small>Validation du projet</small></div></div><div className="workspace-grid"><div className="workspace-card wide"><div className="card-head"><span>DERNIÈRE DEMANDE</span><b>Voir le détail <ChevronRight size={14} /></b></div><h2>Maintenance des installations</h2><p>Demande reçue le 18 juin · Cotonou</p><div className="progress-line"><span style={{ width: "62%" }} /></div><div className="progress-meta"><span>Étude du besoin</span><strong>62%</strong></div></div><div className="workspace-card"><div className="card-head"><span>NOTIFICATIONS</span><Bell size={15} /></div><div className="notification"><CheckCircle2 size={16} /><span>Votre demande a été reçue.<small>Il y a 2 jours</small></span></div><div className="notification"><FileText size={16} /><span>Un nouveau devis est disponible.<small>Il y a 4 jours</small></span></div></div></div></section>{quoteService && <QuoteRequest serviceId={quoteService} />}</div></main>;
}

function ManageServices({ publisher }: { publisher: string }) {
  const [items, setItems] = useState<ServiceItem[]>(getServices());
  const [title, setTitle] = useState("");
  const [category, setCategory] = useState(publisher.includes("Financier") ? "Finance" : publisher.includes("Immobilier") ? "Immobilier" : publisher.includes("BTP") ? "BTP" : publisher.includes("Entretien") ? "Entretien & sécurité" : "Services");
  const [description, setDescription] = useState("");
  const publish = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!title.trim() || !description.trim()) return; publishService({ title: title.trim(), category, description: description.trim(), priceLabel: "Sur devis", publisher, published: true }); setItems(getServices()); setTitle(""); setDescription(""); };
  return <section className="manage-services"><div className="manage-heading"><div><div className="public-kicker">CATALOGUE · PUBLICATION</div><h2>Publier une<br /><em>prestation.</em></h2><p>Les prestations publiées apparaissent immédiatement sur la page publique. En production, cette action devra être protégée par une permission backend.</p></div><div className="manage-permission"><ShieldCheck size={18} /><span>Permission active<strong>{publisher}</strong></span></div></div><form className="service-form" onSubmit={publish}><label>Nom de la prestation<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex. Suivi de chantier" required /></label><label>Domaine<select value={category} onChange={(event) => setCategory(event.target.value)}><option>BTP</option><option>Immobilier</option><option>Entretien & sécurité</option><option>RH</option><option>Services</option><option>Finance</option></select></label><label className="full-field">Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Décrivez la prestation en quelques lignes" required /></label><button className="primary-action" type="submit">Publier sur le site public <ArrowRight size={16} /></button></form><div className="managed-list"><div className="managed-list-head"><span>PRESTATIONS PUBLIÉES</span><strong>{items.filter((item) => item.published).length}</strong></div>{items.filter((item) => item.published).slice(0, 6).map((item) => <div className="managed-item" key={item.id}><div><strong>{item.title}</strong><span>{item.category} · {item.publisher}</span></div><button type="button" onClick={() => { removeService(item.id); setItems(getServices()); }} aria-label={`Retirer ${item.title}`}>Retirer</button></div>)}</div></section>;
}

export function InternalArea({ area }: { area: typeof internalAreas[number] }) {
  const Icon = area.icon;
  return <main className={`internal-page ${area.color}`}><header className="internal-header"><a className="mks-brand" href="/#top"><span className="mks-mark">MKS</span><span><strong>MKS</strong><small>SERVICE</small></span></a><span className="internal-breadcrumb">ESPACE PRIVÉ · {area.name.toUpperCase()}</span><a className="logout-button" href="/#client">Retour espace client <ArrowRight size={15} /></a></header><section className="internal-hero"><div className="internal-icon"><Icon size={30} /></div><div><div className="public-kicker">Accès interne · {area.hash}</div><h1>{area.name}<br /><em>en contrôle.</em></h1><p>{area.text} Cette interface est réservée aux comptes autorisés et sera reliée à l’API MKS Service.</p></div></section><section className="internal-panels"><div className="internal-panel"><span>STATUT DE L’ESPACE</span><strong>Prêt à connecter</strong><small>Authentification et permissions à brancher côté serveur.</small></div><div className="internal-panel"><span>PROCHAINE ACTION</span><strong>Définir les rôles</strong><small>Chaque permission doit être vérifiée côté backend.</small></div><div className="internal-panel"><span>JOURNAL</span><strong>Traçabilité active</strong><small>Les événements sensibles seront conservés et consultables.</small></div></section>{(area.name.startsWith("Admin") || area.name.startsWith("Responsable")) && <ManageServices publisher={area.name} />}</main>;
}

export function AccessRequired({ area }: { area: string }) { return <main className="access-required"><div className="access-required-card"><div className="form-kicker"><LockKeyhole size={16} /> ACCÈS RÉSERVÉ</div><h1>{area}<br /><em>nécessite une connexion.</em></h1><p>Connectez-vous avec un compte autorisé pour accéder à cet espace MKS Service.</p><a className="primary-action" href="/login">Se connecter <ArrowRight size={16} /></a><a className="back-public-link" href="/#top"><ArrowLeft size={15} /> Retour au site public</a></div></main>; }

export { internalAreas };
