-- MKS Service — schéma PostgreSQL autonome
-- Ce fichier est séparé de la base active et ne doit être exécuté qu’après
-- configuration d’une DATABASE_URL PostgreSQL dédiée.

BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE user_role AS ENUM ('user', 'admin');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  open_id varchar(64) NOT NULL UNIQUE,
  name text,
  email varchar(320),
  login_method varchar(64),
  role user_role NOT NULL DEFAULT 'user',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_signed_in timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS services (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(180) NOT NULL,
  category varchar(80) NOT NULL,
  description text NOT NULL,
  price_label varchar(120) NOT NULL,
  price_amount numeric(14, 2),
  image_key varchar(512),
  image_url varchar(768),
  publisher_id integer NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  publisher_name varchar(255) NOT NULL,
  published boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT services_price_amount_nonnegative CHECK (price_amount IS NULL OR price_amount >= 0)
);

CREATE INDEX IF NOT EXISTS services_published_created_idx ON services (published, created_at DESC);
CREATE INDEX IF NOT EXISTS services_category_idx ON services (category);
CREATE INDEX IF NOT EXISTS services_price_amount_idx ON services (price_amount);

COMMIT;
